### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by Directory** [polakowo/gpt2bot#4]
I've modified the source code of interactive_bot.py and stripped it down significantly. the only thing left is a function that takes in a single string (initial message) and then it returns a response of the message without any history to go off of. the class arguments you see passed into `generate_response` are the same normal args that would be passed in in the original script.
```
def response(self, initial):
    history = initial + self.tokenizer.eos_token
    possibilities = generate_response(self.model, self.tokenizer, history, self.config)
    return random.choice(possibilities)
```
I'm running this function on every comment from a comments section on a meme web app just to see what kind of responses it would make. the function is ran maybe 1 to 2 times a second. usually around 50 executions of the function in called and a crash occurs. the traceback is quite long and usually its different too. 
```
...
C:/w/1/s/windows/pytorch/aten/src\THC/THCTensorRandom.cuh:166: block: [2,0,0], thread: [926,0,0] Assertion `THCNumerics<T>::ge(val, zero)` failed.
C:/w/1/s/windows/pytorch/aten/src\THC/THCTensorRandom.cuh:166: block: [2,0,0], thread: [927,0,0] Assertion `THCNumerics<T>::ge(val, zero)` failed.
Traceback (most recent call last):
  File "D:/Documents/Python Stuff/NAPB project/scripts/comment_spooker/comment_spooker.py", line 47, in <module>
    res = sentience.response(comment)
  File "D:\Documents\Python Stuff\NAPB project\scripts\comment_spooker\gen_single_response.py", line 27, in response
    possibilities = generate_response(self.model, self.tokenizer, history, self.config)
  File "D:\Documents\Python Stuff\NAPB project\scripts\comment_spooker\decoder.py", line 82, in generate_response
    out = sample_sequence(model, context_tokens, config)
  File "D:\Documents\Python Stuff\NAPB project\scripts\comment_spooker\decoder.py", line 60, in sample_sequence
    outputs = model(**inputs)  # Note: we could also use 'past' with GPT-2/Transfo-XL/XLNet/CTRL (cached hidden-states)
  File "D:\Program Files\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Program Files\Python37\lib\site-packages\transformers\modeling_gpt2.py", line 549, in forward
    inputs_embeds=inputs_embeds)
  File "D:\Program Files\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Program Files\Python37\lib\site-packages\transformers\modeling_gpt2.py", line 460, in forward
    head_mask=head_mask[i])
  File "D:\Program Files\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Program Files\Python37\lib\site-packages\transformers\modeling_gpt2.py", line 232, in forward
    head_mask=head_mask)
  File "D:\Program Files\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Program Files\Python37\lib\site-packages\transformers\modeling_gpt2.py", line 191, in forward
    present = torch.stack((key.transpose(-2, -1), value))  # transpose to have same shapes for stacking
RuntimeError: CUDA error: device-side assert triggered
C:/w/1/s/windows/pytorch/aten/src\THC/THCTensorRandom.cuh:166: block: [2,0,0], thread: [800,0,0] Assertion `THCNumerics<T>::ge(val, zero)` failed.
C:/w/1/s/windows/pytorch/aten/src\THC/THCTensorRandom.cuh:166: block: [2,0,0], thread: [801,0,0] Assertion `THCNumerics<T>::ge(val, zero)` failed.
C:/w/1/s/windows/pytorch/aten/src\THC/THCTensorRandom.cuh:166: block: [2,0,0], thread: [802,0,0] Assertion `THCNumerics<T>::ge(val, zero)` failed.
C:/w/1/s/windows/pytorch/aten/src\THC/THCTensorRandom.cuh:166: block: [2,0,0], thread: [803,0,0] Assertion `THCNumerics<T>::ge(val, zero)` failed.
C:/w/1/s/windows/pytorch/aten/src\THC/THCTensorRandom.cuh:166: block: [2,0,0], thread: [804,0,0] Assertion `THCNumerics<T>::ge(val, zero)` failed.
...
```
another traceback ive seen is 
```
THCudaCheck FAIL file=C:/w/1/s/windows/pytorch/aten/src\ATen/native/cuda/Normalization.cuh line=586 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "D:/Documents/Python Stuff/NAPB project/scripts/comment_spooker/comment_spooker.py", line 47, in <module>
    res = sentience.response(comment)
  File "D:\Documents\Python Stuff\NAPB project\scripts\comment_spooker\gen_single_response.py", line 27, in response
    possibilities = generate_response(self.model, self.tokenizer, history, self.config)
  File "D:\Documents\Python Stuff\NAPB project\scripts\comment_spooker\decoder.py", line 82, in generate_response
    out = sample_sequence(model, context_tokens, config)
  File "D:\Documents\Python Stuff\NAPB project\scripts\comment_spooker\decoder.py", line 60, in sample_sequence
    outputs = model(**inputs)  # Note: we could also use 'past' with GPT-2/Transfo-XL/XLNet/CTRL (cached hidden-states)
  File "D:\Program Files\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Program Files\Python37\lib\site-packages\transformers\modeling_gpt2.py", line 549, in forward
    inputs_embeds=inputs_embeds)
  File "D:\Program Files\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Program Files\Python37\lib\site-packages\transformers\modeling_gpt2.py", line 460, in forward
    head_mask=head_mask[i])
  File "D:\Program Files\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Program Files\Python37\lib\site-packages\transformers\modeling_gpt2.py", line 229, in forward
    output_attn = self.attn(self.ln_1(x),
  File "D:\Program Files\Python37\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Program Files\Python37\lib\site-packages\torch\nn\modules\normalization.py", line 152, in forward
    input, self.normalized_shape, self.weight, self.bias, self.eps)
  File "D:\Program Files\Python37\lib\site-packages\torch\nn\functional.py", line 1682, in layer_norm
    torch.backends.cudnn.enabled)
RuntimeError: cuda runtime error (59) : device-side assert triggered at C:/w/1/s/windows/pytorch/aten/src\ATen/native/cuda/Normalization.cuh:586
```
restarting the program works right back up immidiatly however if i try to make a try except to skip over that comment and go to the next one the error still raises, same applys for trying again, and even loading the model and tokenizer again. if i try loading them again it raises an exception immediatly. i have an rtx 2080 super and a ryzen 9 3900x if that helps.

**Comment by polakowo** [comment]
Rerun with environmental variable CUDA_LAUNCH_BLOCKING=1 and see what line it crashed on. It’s also useful to trace back the comment that caused the crash, maybe there is some sort of out-of-bounds error on embeddings lookup. You will have to solve the issue otherwise the only way to run the things again is to restart the program.

**Comment by Directory** [comment]
sorry for the late response but this is the traceback im getting
```
Traceback (most recent call last):
  File "D:/Documents/Python Stuff/NAPB project/scripts/comment_spooker/comment_spooker.py", line 85, in <module>
    res = sentience.response(comment)
  File "D:\Documents\Python Stuff\NAPB project\scripts\comment_spooker\gen_single_response.py", line 27, in response
    possibilities = generate_response(self.model, self.tokenizer, history, self.config)
  File "D:\Documents\Python Stuff\NAPB project\scripts\comment_spooker\decoder.py", line 82, in generate_response
    out = sample_sequence(model, context_tokens, config)
  File "D:\Documents\Python Stuff\NAPB project\scripts\comment_spooker\decoder.py", line 67, in sample_sequence
    generated = torch.cat((generated, next_token), dim=1)
RuntimeError: cuda runtime error (59) : device-side assert triggered at ..\aten\src\THC\THCGeneral.cpp:371

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Documents/Python Stuff/NAPB project/scripts/comment_spooker/comment_spooker.py", line 89, in <module>
    sentience = Response()
  File "D:\Documents\Python Stuff\NAPB project\scripts\comment_spooker\gen_single_response.py", line 21, in __init__
    self.model, self.tokenizer = load_model(target_dir, config)
  File "D:\Documents\Python Stuff\NAPB project\scripts\comment_spooker\model.py", line 110, in load_model
    state_dict = torch.load(state_dict_path, map_location=device)
  File "D:\Program Files\Python37\lib\site-packages\torch\serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "D:\Program Files\Python37\lib\site-packages\torch\serialization.py", line 573, in _load
    result = unpickler.load()
  File "D:\Program Files\Python37\lib\site-packages\torch\serialization.py", line 536, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "D:\Program Files\Python37\lib\site-packages\torch\serialization.py", line 406, in restore_location
    return default_restore_location(storage, str(map_location))
  File "D:\Program Files\Python37\lib\site-packages\torch\serialization.py", line 119, in default_restore_location
    result = fn(storage, location)
  File "D:\Program Files\Python37\lib\site-packages\torch\serialization.py", line 99, in _cuda_deserialize
    return storage_type(obj.size())
RuntimeError: CUDA error: device-side assert triggered
```

**Comment by polakowo** [comment]
The assertion error raises in `generated = torch.cat((generated, next_token), dim=1)`, you can try to debug this line by printing the contents of the variables `generated` and `next_token`. Also print out the shape of `generated`. Then see how those differ from the successful runs.

**Comment by Directory** [comment]
it seems ive been able to sort of fix the issue by setting num_samples to 1. not my preference but it works. cutting corners until its close enough is the sign of a True programmer so ill just do that from now on.
